security:

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    doc:
      pattern: ^/api/doc
      lazy: true
      anonymous: true
    login:
      pattern: ^/api/login_check$
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    special_api:
      pattern: ^/api/volume/106/secret$
      stateless: true
      logout: ~
      guard:
        authenticators:
          - App\Security\VolumeTokenAuthenticator
      provider: app_user_provider
    api:
      pattern: ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  encoders:
    App\Entity\User:
      algorithm: auto

  access_control:
    - { path: ^/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/doc(\.json)?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/volume/106/secret$, roles: [ IS_AUTHENTICATED_FULLY, ROLE_DEVICE ] }
    - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }
